apiVersion: app/v1
kind: Deployment
metadata:
  name: sejutacita_app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: sejutacita_app
        image: tsaqifrazinn/sejutacita:1.0
        ports:
        - containerPort: 3000