apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sejutacita-app
  template:
    metadata:
      labels:
        app: sejutacita-app
    spec:
      containers:
      - name: sejutacita-app
        image: tsaqifrazinn/sejutacita:1.0
        env:
          - name : JWT_SECRET
            value : secret
          - name : REF_TOKEN_SECRET
            value : refsecret
          - name : PORT
            value : "3000"
          - name : DB_URI 
            value : mongodb+srv://sejuta-cita:sejuta-cita@sejutacita.iv72x.mongodb.net/user?retryWrites=true&w=majority
        ports:
        - containerPort: 3000