apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sejutacita-app
  template:
    metadata:
      labels:
        app: sejutacita-app
    spec:
      containers:
      - name: sejutacita-app
        image: tsaqifrazinn/sejutacita:1.0
        env:
          - name : JWT_SECRET
            value : secret
          - name : REF_TOKEN_SECRET
            value : refsecret
          - name : PORT
            value : 3000
          - name : DB_URI 
            value : mongodb://mongo:27017/sejuta-cita
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 20
          periodSeconds: 5
        ports:
        - containerPort: 3000