apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sejutacita-app
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: sejutacita-app
        image: tsaqifrazinn/sejutacita:1.0
        ports:
        - containerPort: 3000